# FORTEMEDIA Platform Support


snd-soc-im501-sound-objs := im501_sound.o
obj-$(CONFIG_SND_SOC_IM501_SOUND) += snd-soc-im501-sound.o

#snd-soc-im501-sound-objs := im501_sound.o
#obj-$(CONFIG_SND_SOC_IM501_SOUND) += im501_sound.o
